# -*-coding:UTF-8 -*-
from selenium import webdriver
driver = webdriver.Chrome('../drivers/chromedriver.exe')
driver.get('http://192.168.1.4/ecshop/admin')
driver.maximize_window()
driver.find_element_by_name('username').send_keys('caichang')
driver.find_element_by_name('password').send_keys('caichang1')
driver.find_element_by_class_name('btn-a').click()
driver.switch_to.frame('menu-frame')
driver.find_element_by_link_text('商品列表').click()
driver.switch_to.default_content()
driver.switch_to.frame('main-frame')
driver.find_element_by_xpath('//*[@id="listDiv"]/table[1]/tbody/tr[3]/td[12]/a[4]/img').click()
driver.switch_to.alert.accept()
driver.switch_to.default_content()
driver.switch_to.frame('menu-frame')
driver.find_element_by_link_text('商品回收站').click()
driver.switch_to.default_content()
driver.switch_to.frame('main-frame')
driver.find_element_by_xpath('//*[@id="listDiv"]/table[1]/tbody/tr[3]/td[5]/a[2]').click()
driver.switch_to.alert.accept()
